version: '2'
services:
    sbnz-app:
        image: sbnz
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://sbnz-postgresql:5432/sbnz
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    sbnz-postgresql:
        extends:
            file: postgresql.yml
            service: sbnz-postgresql
